"""drop room_states mob_states column

Revision ID: 70a9c771b610
Revises: bf6901ef8aa9
Create Date: 2026-04-12 12:27:03.356237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '70a9c771b610'
down_revision: Union[str, Sequence[str], None] = 'bf6901ef8aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_states', 'mob_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_states', sa.Column('mob_states', sa.JSON(), nullable=False))
    # ### end Alembic commands ###
