"""add card_type to cards

Revision ID: 7fe8790a5b56
Revises: 70a9c771b610
Create Date: 2026-04-12 21:49:07.840604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe8790a5b56'
down_revision: Union[str, Sequence[str], None] = '70a9c771b610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_type', sa.String(length=30), server_default=sa.text("'physical'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'card_type')
    # ### end Alembic commands ###
