"""initial schema

Revision ID: bf6901ef8aa9
Revises: 
Create Date: 2026-04-11 20:49:52.022091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6901ef8aa9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_card_key'), 'cards', ['card_key'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('charges', sa.Integer(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('usable_in_combat', sa.Boolean(), nullable=False),
    sa.Column('usable_outside_combat', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('tradeable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_item_key'), 'items', ['item_key'], unique=True)
    op.create_table('player_object_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('room_key', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=50), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'room_key', 'object_id', name='uq_player_room_object')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('inventory', sa.JSON(), nullable=False),
    sa.Column('card_collection', sa.JSON(), nullable=False),
    sa.Column('current_room_id', sa.String(length=50), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('visited_rooms', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('room_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_key', sa.String(length=50), nullable=False),
    sa.Column('mob_states', sa.JSON(), nullable=False),
    sa.Column('dynamic_state', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_states_room_key'), 'room_states', ['room_key'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('tile_data', sa.JSON(), nullable=False),
    sa.Column('exits', sa.JSON(), nullable=False),
    sa.Column('objects', sa.JSON(), nullable=False),
    sa.Column('spawn_points', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_room_key'), 'rooms', ['room_key'], unique=True)
    op.create_table('spawn_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_key', sa.String(length=50), nullable=False),
    sa.Column('room_key', sa.String(length=50), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currently_spawned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spawn_checkpoints')
    op.drop_index(op.f('ix_rooms_room_key'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_room_states_room_key'), table_name='room_states')
    op.drop_table('room_states')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    op.drop_table('player_object_states')
    op.drop_index(op.f('ix_items_item_key'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_cards_card_key'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
